name: Build Website (Staging)

on:
  push:
    branches: [ staging ]
    paths:
      - 'services/website/src/adapools.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Build static website
      working-directory: ./services/website
      env: # Or as an environment variable
        BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        npm install
        node src/scripts/generatePages.js
        npm run build
        npm run export
        git config --global user.name "${{ secrets.CI_USERNAME }}"
        git config --global user.email "${{ secrets.CI_EMAIL }}"
        PAT64=$(echo ":${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base64)
        git -c http.extraHeader="Authorization: Basic $PAT64" clone https://${{ secrets.CI_USERNAME }}:${{ secrets.CI_PASSWORD }}@github.com/ada-pi-machine/ada-pi-machine.github.io.git /tmp/repo
        cp src/topology.json src/schema.json src/pools.json src/pools_extended.json src/topology.json src/adapools.json src/translations.json src/languages.json src/pages.json /tmp/repo/
        rm -rf /tmp/repo/_next
        rm -rf /tmp/repo/page-data
        cp -R out/* /tmp/repo
        cp -R src/page-data/* /tmp/repo/page-data
    - name: Push changes to GitHub Pages repo
      working-directory: /tmp/repo
      run: |
        pwd
        git add --all 
        git commit -m 'update build' 
        git config --global user.name "${{ secrets.CI_USERNAME }}"
        git config --global user.email "${{ secrets.CI_EMAIL }}"
        git remote set-url origin https://${{ secrets.CI_USERNAME }}:${{ secrets.CI_PASSWORD }}@github.com/ada-pi-machine/ada-pi-machine.github.io.git
        git push origin master