name: Build Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: build
      working-directory: ./services/website
      run: |
        npm install
        npm run build
        npm run export
        git clone https://keyflight:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ADA-pi/ada-pi.github.io repo
        git config user.name "keyflight"
        git config user.email "olivier@andev.nl"

        cat repo/README.md
        mkdir updated_repo
        cp -R repo/.git repo/README.md updated_repo
        cp -R out/* updated_repo
        cd updated_repo
        git add --all
        git commit -m 'update build'
        git push origin master