name: Build Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: build
      working-directory: ./services/website
      run: |
        npm install
        npm run build
        npm run export
        git config --global user.name "keyflight"
        git config --global user.email "olivier@andev.nl"
        PAT64=$(echo ":${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base64)
        git -c http.extraHeader="Authorization: Basic $PAT64" clone https://github.com/ADA-Pi/pi-alliance.git /tmp/repo
        cat /tmp/repo/README.md
        mkdir /tmp/updated_repo
        cp -R /tmp/repo/.git /tmp/repo/README.md /tmp/updated_repo
        cp -R out/* /tmp/updated_repo
    - name: build
      working-directory: /tmp/updated_repo
      run: |
        pwd
        git add --all 
        git commit -m 'update build' 
        PAT64=$(echo ":${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base64)
        git -c http.extraHeader="Authorization: Basic $PAT64" push origin master