name: Build Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: build
      working-directory: ./services/website
      run: |
        npm install
        npm run build
        npm run export
    - name: build
      working-directory: /tmp/repo
      run: |
        pwd
        git config --global user.name "keyflight"
        git config --global user.email "olivier@andev.nl"
        PAT64=$(echo ":${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base64)
        git -c http.extraHeader="Authorization: Basic $PAT64" clone https://github.com/ADA-Pi/pi-alliance.git .
        cat /README.md
        cp -R /home/runner/work/pi-alliance/pi-alliance/services/website/* .
        git add --all 
        git commit -m 'update build' 
        git -c http.extraHeader="Authorization: Basic $PAT64" push origin master